<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
	<RootNamespace>EtAlii.Adp.Client</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazor.Bootstrap" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all" />

<!--    <PackageReference Include="Microsoft.AspNetCore.Components" />-->
<!--    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />-->
<!--    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />-->
<!--    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" />-->
<!--    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all"  />-->
    <PackageReference Include="Z.Blazor.Diagrams.Algorithms" />
    <PackageReference Include="Z.Blazor.Diagrams.Core" />
    <PackageReference Include="Z.Blazor.Diagrams" />
  </ItemGroup>


  <ItemGroup>
	<ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>


  <ItemGroup>
    <Folder Include="Configuration\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Navigation\NavHeader.Debug.razor.cs">
      <DependentUpon>NavHeader.razor</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
