namespace EtAlii.Adp.Diagram.DependencyGraph.Tests.Parity;

/// <summary>
/// The documents the parity transcript records beside the fixtures and the examples: the cases the
/// rule, parser and provider tests state inline, and the combinations none of them states, each under
/// a name that says what it is for.
/// </summary>
/// <remarks>
/// <para>
/// <b>The fixtures are about text and none of them breaks a rule</b>, so without these the transcript
/// would freeze no finding at all. Every rule is here alone, and here beside the others in the orders
/// that tell one ordering of the findings from another.
/// </para>
/// <para>
/// <b>LF line endings and a final newline</b>, as the tests' raw string literals give them; the
/// fixtures carry the CRLF and no-final-newline cases.
/// </para>
/// </remarks>
internal static class DependencyGraphCorpus
{
    /// <summary>The inline documents, by name, in the order the transcript records them.</summary>
    public static IReadOnlyList<(string Name, string Text)> Inline { get; } =
    [
        ("inline/new-document", "dependencies: 1\r\nelements: []\r\n"),
        ("inline/empty", ""),
        ("inline/not-yaml", "dependencies: 1\nelements:\n  - id: aaa\n    label: [unclosed\n"),
        ("inline/root-not-a-mapping", "- just\n- a list\n"),
        ("inline/no-elements-key", "dependencies: 1\ntitle: Nothing declared\n"),
        ("inline/missing-id", Lines(
            "dependencies: 1",
            "elements:",
            "  - label: Anonymous",
            "    x: 0",
            "    row: 0",
            "  - x: 200",
            "    row: 1",
            "  - id: \"\"",
            "    label: Empty id",
            "    x: 400",
            "    row: 2",
            "  - id: named",
            "    label: Named",
            "    x: 600",
            "    row: 0",
            "relations:",
            "  - from: named",
            "    to: named2",
            "  - id: \"\"",
            "    from: named",
            "    to: named")),
        ("inline/duplicate-id", Lines(
            "dependencies: 1",
            "elements:",
            "  - id: aaa",
            "    label: First",
            "    x: 0",
            "    row: 0",
            "  - id: aaa",
            "    label: Second",
            "    x: 200",
            "    row: 1",
            "  - id: aaa",
            "    label: Third",
            "    x: 400",
            "    row: 2",
            "  - id: bbb",
            "    label: Other",
            "    x: 600",
            "    row: 0",
            "relations:",
            "  - id: bbb",
            "    from: aaa",
            "    to: bbb",
            "  - id: ccc",
            "    from: bbb",
            "    to: aaa",
            "  - id: ccc",
            "    from: aaa",
            "    to: bbb",
            "    label: again")),
        ("inline/dangling-relation", Lines(
            "dependencies: 1",
            "elements:",
            "  - id: aaa",
            "    label: Present",
            "    x: 0",
            "    row: 0",
            "relations:",
            "  - id: to-ghost",
            "    from: aaa",
            "    to: ghost",
            "  - id: from-ghost",
            "    from: ghost",
            "    to: aaa",
            "  - id: both-ghosts",
            "    from: ghost1",
            "    to: ghost2",
            "    label: between nobodies",
            "  - id: no-from",
            "    to: aaa",
            "  - id: empty-to",
            "    from: aaa",
            "    to: \"\"")),
        ("inline/self-dependency", Lines(
            "dependencies: 1",
            "elements:",
            "  - id: aaa",
            "    label: Needs itself",
            "    x: 0",
            "    row: 0",
            "relations:",
            "  - id: ccc",
            "    from: aaa",
            "    to: aaa",
            "    label: loops")),
        ("inline/every-rule-interleaved", Lines(
            "dependencies: 1",
            "elements:",
            "  - id: aaa",
            "    label: First",
            "    x: 0",
            "    row: 0",
            "  - id: aaa",
            "    label: Repeats the first",
            "    x: 240",
            "    row: 0",
            "  - label: Has no id",
            "    x: 480",
            "    row: 1",
            "  - id: bbb",
            "    label: Second",
            "    x: 720",
            "    row: 1",
            "relations:",
            "  - id: loop",
            "    from: bbb",
            "    to: bbb",
            "  - id: dangles",
            "    from: bbb",
            "    to: ghost",
            "  - id: loop-and-dangling",
            "    from: ghost",
            "    to: ghost",
            "  - from: aaa",
            "    to: bbb",
            "  - id: dangles",
            "    from: aaa",
            "    to: nobody")),
        ("inline/relations-before-elements", Lines(
            "dependencies: 1",
            "relations:",
            "  - id: shared",
            "    from: aaa",
            "    to: bbb",
            "elements:",
            "  - id: aaa",
            "    label: Declared after the relations",
            "    x: 0",
            "    row: 0",
            "  - id: shared",
            "    label: Shares the relation's id",
            "    x: 240",
            "    row: 1",
            "  - id: bbb",
            "    x: 480",
            "    row: 2")),
        ("inline/unreadable-values", Lines(
            "dependencies: 1",
            "elements:",
            "  - id: aaa",
            "    x: sideways",
            "    row: sideways",
            "  - id: bbb",
            "    label: Fractional row",
            "    x: 1e3",
            "    row: 1.5",
            "  - just a string",
            "  - id: ccc",
            "    label:",
            "    x: -0.25",
            "    row: -3",
            "relations:",
            "  - not a mapping",
            "  - id: rel",
            "    from: aaa",
            "    to: bbb")),
        ("inline/far-and-fine-coordinates", Lines(
            "dependencies: 1",
            "elements:",
            "  - id: far",
            "    label: A million across",
            "    x: 1000000",
            "    row: 0",
            "  - id: fine",
            "    label: A hundred-thousandth across",
            "    x: 0.00001",
            "    row: 1",
            "  - id: huge",
            "    label: Past every screen",
            "    x: 1e21",
            "    row: 2",
            "  - id: signed-zero",
            "    label: Minus nothing",
            "    x: -0",
            "    row: -1",
            "relations:",
            "  - id: across",
            "    from: far",
            "    to: fine")),
    ];

    private static string Lines(params string[] lines) => string.Join("\n", lines) + "\n";
}
