/**
 * The ruler's ladder: which time boundaries deserve a label for a given visible span, and where
 * they fall.
 *
 * A pure function of (visible range, width in pixels) - no component, no DOM - because
 * Requirement 5.4 is the one the spec flags as most likely to be got wrong, and a pure function
 * is the only shape that lets it be tested across the whole zoom range rather than eyeballed at
 * one.
 */

export interface TimelineTick {
  /** Where the boundary falls, in seconds since the epoch - the module's own x axis. */
  seconds: number;
  label: string;
}

const SECOND = 1;
const MINUTE = 60;
const HOUR = 3600;
const DAY = 86400;
const WEEK = 7 * DAY;

/** A labelled tick needs roughly this many pixels or the labels collide. */
const MIN_LABEL_SPACING_PX = 80;

/**
 * The fixed-duration rungs. Months, quarters and years are not fixed durations, so they are
 * generated by calendar walking below rather than listed here.
 */
const FIXED_STEPS: readonly number[] = [
  SECOND,
  15 * SECOND,
  MINUTE,
  5 * MINUTE,
  15 * MINUTE,
  HOUR,
  6 * HOUR,
  DAY,
  WEEK,
];

/**
 * The labelled boundaries for the visible range, on round boundaries of a step chosen so labels
 * neither crowd nor vanish (Requirements 5.4, 5.5).
 *
 * Boundaries are round in UTC, matching the module's whole-time policy: times are taken at face
 * value with no timezone, so the ruler must not shift labels by the viewer's offset - the same
 * document shows the same ruler on every machine.
 */
export function ticksFor(startSeconds: number, endSeconds: number, widthPx: number): TimelineTick[] {
  if (!(endSeconds > startSeconds) || !(widthPx > 0)) {
    return [];
  }

  const span = endSeconds - startSeconds;
  const maxTicks = Math.max(1, Math.floor(widthPx / MIN_LABEL_SPACING_PX));
  const coarsest = span / maxTicks;

  const fixed = FIXED_STEPS.find((step) => step >= coarsest);
  if (fixed !== undefined) {
    return fixedTicks(startSeconds, endSeconds, fixed);
  }

  // Beyond a week the calendar takes over: a month is not a fixed number of seconds, and a
  // label on "the 1st" is what a reader expects, not one every 2,629,746 seconds.
  if (coarsest <= 31 * DAY) {
    return monthTicks(startSeconds, endSeconds, 1);
  }

  if (coarsest <= 93 * DAY) {
    return monthTicks(startSeconds, endSeconds, 3);
  }

  const yearsPerTick = Math.max(1, Math.ceil(coarsest / (366 * DAY)));
  return yearTicks(startSeconds, endSeconds, yearsPerTick);
}

function fixedTicks(startSeconds: number, endSeconds: number, step: number): TimelineTick[] {
  const ticks: TimelineTick[] = [];
  const first = Math.ceil(startSeconds / step) * step;
  for (let at = first; at <= endSeconds; at += step) {
    ticks.push({ seconds: at, label: labelFor(at, step) });
  }

  return ticks;
}

function monthTicks(startSeconds: number, endSeconds: number, monthsPerTick: number): TimelineTick[] {
  const ticks: TimelineTick[] = [];
  const start = new Date(startSeconds * 1000);
  let year = start.getUTCFullYear();
  let month = Math.ceil(start.getUTCMonth() / monthsPerTick) * monthsPerTick;

  for (;;) {
    const at = Date.UTC(year, month, 1) / 1000;
    if (at > endSeconds) {
      return ticks;
    }

    if (at >= startSeconds) {
      const date = new Date(at * 1000);
      ticks.push({
        seconds: at,
        label:
          date.getUTCMonth() === 0
            ? String(date.getUTCFullYear())
            : `${MONTHS[date.getUTCMonth()]} ${date.getUTCFullYear()}`,
      });
    }

    month += monthsPerTick;
    if (month >= 12) {
      month -= 12;
      year += 1;
    }
  }
}

function yearTicks(startSeconds: number, endSeconds: number, yearsPerTick: number): TimelineTick[] {
  const ticks: TimelineTick[] = [];
  const startYear = new Date(startSeconds * 1000).getUTCFullYear();
  let year = Math.ceil(startYear / yearsPerTick) * yearsPerTick;

  for (;;) {
    const at = Date.UTC(year, 0, 1) / 1000;
    if (at > endSeconds) {
      return ticks;
    }

    if (at >= startSeconds) {
      ticks.push({ seconds: at, label: String(year) });
    }

    year += yearsPerTick;
  }
}

const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

function labelFor(seconds: number, step: number): string {
  const date = new Date(seconds * 1000);
  if (step >= DAY) {
    // A day or week boundary: the date, with the month when it carries new information.
    return date.getUTCDate() === 1
      ? `${MONTHS[date.getUTCMonth()]} ${date.getUTCFullYear()}`
      : `${MONTHS[date.getUTCMonth()]} ${date.getUTCDate()}`;
  }

  if (step >= MINUTE) {
    const hours = String(date.getUTCHours()).padStart(2, "0");
    const minutes = String(date.getUTCMinutes()).padStart(2, "0");
    return `${hours}:${minutes}`;
  }

  const h = String(date.getUTCHours()).padStart(2, "0");
  const m = String(date.getUTCMinutes()).padStart(2, "0");
  const s = String(date.getUTCSeconds()).padStart(2, "0");
  return `${h}:${m}:${s}`;
}
