using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using EtAlii.Adp.Context;
using Google.Protobuf;
using Google.Protobuf.Reflection;

namespace EtAlii.Adp.Diagram.AgentBehaviorModelling.Tests.Parity;

/// <summary>
/// How a parity transcript writes what today's code answers: one canonical line per action, row,
/// finding and payload, so a change to any of them is a one-line diff of the checked-in file.
/// </summary>
/// <remarks>
/// <para>
/// <b>Deterministic by construction</b>: no timestamps, no paths but the corpus's own relative
/// ones, invariant number formatting, and every list in the order the code produced it.
/// </para>
/// <para>
/// <b>CRLF, as <c>.gitattributes</c> checks a JSON file out</b>, so the regenerated bytes compare
/// equal to the working file on every machine.
/// </para>
/// </remarks>
internal static class TranscriptText
{
    /// <summary>The writer every transcript uses.</summary>
    public static JsonWriterOptions WriterOptions { get; } = new()
    {
        Indented = true,
        IndentSize = 2,
        NewLine = "\r\n",
        Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
    };

    private static readonly UTF8Encoding _strictUtf8 = new(encoderShouldEmitUTF8Identifier: false, throwOnInvalidBytes: true);

    // Fields at their default are left out, as the wire leaves them out: the bytes cannot tell them apart.
    private static readonly JsonFormatter _payloadJson = new(JsonFormatter.Settings.Default);

    /// <summary>The lowercase hex sha256 of <paramref name="bytes"/>.</summary>
    public static string Sha256(ReadOnlySpan<byte> bytes) => Convert.ToHexStringLower(SHA256.HashData(bytes));

    /// <summary>The text of a document's bytes, byte-order mark included; invalid UTF-8 throws rather than being repaired.</summary>
    public static string Decode(byte[] bytes) => _strictUtf8.GetString(bytes);

    /// <summary>The bytes of a (masked) text, for hashing.</summary>
    public static byte[] Encode(string text) => _strictUtf8.GetBytes(text);

    /// <summary>A number as the transcript writes it: shortest round-trip, invariant.</summary>
    private static string Number(double value) => value.ToString("R", CultureInfo.InvariantCulture);

    /// <summary>A menu as lines: one per action, prefixed by its group's number, children indented below it.</summary>
    public static IReadOnlyList<string> MenuLines(IReadOnlyList<ContextActionGroupDefinition> groups)
    {
        var lines = new List<string>();
        AddMenuLines(lines, groups, "");
        return lines;
    }

    private static void AddMenuLines(List<string> lines, IReadOnlyList<ContextActionGroupDefinition> groups, string indent)
    {
        for (var group = 0; group < groups.Count; group++)
        {
            foreach (var action in groups[group].Actions)
            {
                var shortcut = action.Shortcut is { } key ? Shortcut(key) : "-";
                var availability = action.Available ? "on" : "off";
                var reason = action.UnavailableReason.Length > 0 ? $" ({action.UnavailableReason})" : "";
                lines.Add($"{indent}g{group + 1} {action.Id} | {action.Label} | {action.Icon} | {shortcut} | {availability}{reason}");
                if (action.Children is { } children)
                {
                    AddMenuLines(lines, children, indent + "  ");
                }
            }
        }
    }

    private static string Shortcut(ContextShortcutDefinition key)
    {
        var builder = new StringBuilder();
        if (key.Ctrl)
        {
            builder.Append("Ctrl+");
        }

        if (key.Shift)
        {
            builder.Append("Shift+");
        }

        if (key.Alt)
        {
            builder.Append("Alt+");
        }

        if (key.Meta)
        {
            builder.Append("Meta+");
        }

        return builder.Append(key.Key).ToString();
    }

    /// <summary>A property row as one line; its candidates, when it has any, as an index into <paramref name="choices"/>.</summary>
    public static string RowLine(ContextPropertyDefinition row, List<IReadOnlyList<string>> choices)
    {
        var editable = row.ReadOnlyReason.Length > 0 ? $"read-only ({row.ReadOnlyReason})" : "editable";
        var candidates = "";
        if (row.Candidates is { } list)
        {
            var index = choices.FindIndex(known => known.SequenceEqual(list, StringComparer.Ordinal));
            if (index < 0)
            {
                choices.Add(list);
                index = choices.Count - 1;
            }

            candidates = $" | choices #{index}";
        }

        return $"{row.Id} | {row.Label} | {JsonSerializer.Serialize(row.Value, StringOptions)} | {row.Editor} | {editable} | group {row.Group}{candidates}";
    }

    /// <summary>
    /// How the read-only rows relate to the readable ones, when one sentence says it exactly: "same",
    /// or every editable row made read-only for one reason. Null when the rows must be listed.
    /// </summary>
    public static string? ReadOnlyVariant(IReadOnlyList<string> rows, IReadOnlyList<string> readOnlyRows)
    {
        if (rows.SequenceEqual(readOnlyRows, StringComparer.Ordinal))
        {
            return "same";
        }

        const string editable = " | editable | ";
        var reason = readOnlyRows.Zip(rows)
            .Where(pair => pair.Second.Contains(editable, StringComparison.Ordinal))
            .Select(pair => pair.First[(pair.First.IndexOf(" | read-only (", StringComparison.Ordinal) + 3)..])
            .Select(rest => rest[..(rest.IndexOf(") | group ", StringComparison.Ordinal) + 1)])
            .FirstOrDefault();
        if (reason is null || rows.Count != readOnlyRows.Count)
        {
            return null;
        }

        var expected = rows.Select(row => row.Replace(editable, $" | {reason} | ", StringComparison.Ordinal));
        return expected.SequenceEqual(readOnlyRows, StringComparer.Ordinal) ? $"same, every editable row {reason}" : null;
    }

    /// <summary>A string as a JSON literal, so a value's newlines and quotes stay on its line.</summary>
    public static JsonSerializerOptions StringOptions { get; } = new() { Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping };

    /// <summary>A mapped element as one line, its payload decoded to protobuf JSON.</summary>
    public static string PayloadLine(string id, double x, double y, string type, string typeUrl, ReadOnlyMemory<byte> payload, TypeRegistry registry)
    {
        var name = typeUrl[(typeUrl.LastIndexOf('/') + 1)..];
        var descriptor = registry.Find(name) ?? throw new InvalidOperationException($"No payload type {name} is registered.");
        var message = descriptor.Parser.ParseFrom(payload.Span);
        return $"{id} | {type} | {Number(x)}, {Number(y)} | {descriptor.Name} {_payloadJson.Format(message)}";
    }

    /// <summary>
    /// Writes how <paramref name="before"/> became <paramref name="after"/>: the lines that changed, as
    /// hunks against the text before, and the hash of the whole result.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Hunks rather than the whole document after every step: a hundred-kilobyte example edited twenty
    /// times would otherwise be megabytes of repetition. Applied in order, each hunk replacing
    /// <c>removed</c> lines from <c>line</c> (one-based, counted in the text before the step) with
    /// <c>inserted</c>, they give back the document exactly; the hash pins the whole result anyway.
    /// </para>
    /// <para>
    /// A step that rewrites more than <see cref="MaxHunkText"/> characters - an Arrange of a large
    /// example moves hundreds of rows - is written as its changed-line count and hash alone: still
    /// pinned to the byte, no longer replayable from the transcript.
    /// </para>
    /// </remarks>
    public static void WriteChange(Utf8JsonWriter json, string before, string after)
    {
        if (string.Equals(before, after, StringComparison.Ordinal))
        {
            json.WriteBoolean("unchanged", true);
            return;
        }

        var hunks = Hunks(Lines(before), Lines(after));
        if (hunks.Sum(hunk => hunk.Inserted.Length + 16) > MaxHunkText)
        {
            json.WriteString("summary", $"{hunks.Sum(hunk => hunk.Removed)} lines replaced by {hunks.Sum(hunk => Lines(hunk.Inserted).Count)} in {hunks.Count} hunks");
        }
        else
        {
            json.WriteStartArray("hunks");
            foreach ((int line, int removed, string inserted) in hunks)
            {
                json.WriteStringValue($"@{line} -{removed} +{JsonSerializer.Serialize(inserted, StringOptions)}");
            }

            json.WriteEndArray();
        }

        json.WriteString("sha256", Sha256(Encode(after)));
    }

    /// <summary>The most hunk text a step writes before it is summarised instead.</summary>
    private const int MaxHunkText = 4096;

    /// <summary>A text's lines, each with its own line ending, so joining them gives the text back exactly.</summary>
    private static List<string> Lines(string text)
    {
        var lines = new List<string>();
        var start = 0;
        for (var index = 0; index < text.Length; index++)
        {
            if (text[index] == '\n')
            {
                lines.Add(text[start..(index + 1)]);
                start = index + 1;
            }
        }

        if (start < text.Length)
        {
            lines.Add(text[start..]);
        }

        return lines;
    }

    /// <summary>The hunks that turn <paramref name="before"/> into <paramref name="after"/>, from a longest common subsequence of lines.</summary>
    private static List<(int Line, int Removed, string Inserted)> Hunks(List<string> before, List<string> after)
    {
        var prefix = 0;
        while (prefix < before.Count && prefix < after.Count && before[prefix] == after[prefix])
        {
            prefix++;
        }

        var suffix = 0;
        while (suffix < before.Count - prefix && suffix < after.Count - prefix && before[^(suffix + 1)] == after[^(suffix + 1)])
        {
            suffix++;
        }

        var left = before.GetRange(prefix, before.Count - prefix - suffix);
        var right = after.GetRange(prefix, after.Count - prefix - suffix);
        if ((long)left.Count * right.Count > 16_000_000)
        {
            // Too large a table to be worth it: the whole changed middle as one hunk.
            return [(prefix + 1, left.Count, string.Concat(right))];
        }

        // lengths[i, j]: the longest common subsequence of left[i..] and right[j..].
        var lengths = new int[left.Count + 1, right.Count + 1];
        for (var i = left.Count - 1; i >= 0; i--)
        {
            for (var j = right.Count - 1; j >= 0; j--)
            {
                lengths[i, j] = left[i] == right[j] ? lengths[i + 1, j + 1] + 1 : Math.Max(lengths[i + 1, j], lengths[i, j + 1]);
            }
        }

        var hunks = new List<(int Line, int Removed, string Inserted)>();
        int x = 0, y = 0;
        while (x < left.Count || y < right.Count)
        {
            if (x < left.Count && y < right.Count && left[x] == right[y])
            {
                x++;
                y++;
                continue;
            }

            var hunkStart = x;
            var inserted = new StringBuilder();
            while ((x < left.Count || y < right.Count) && !(x < left.Count && y < right.Count && left[x] == right[y]))
            {
                if (y < right.Count && (x == left.Count || lengths[x, y + 1] >= lengths[x + 1, y]))
                {
                    inserted.Append(right[y++]);
                }
                else
                {
                    x++;
                }
            }

            hunks.Add((prefix + hunkStart + 1, x - hunkStart, inserted.ToString()));
        }

        return hunks;
    }

    /// <summary>The first line at which two transcripts differ, for a failure message a person can act on.</summary>
    public static string FirstDifference(byte[] expected, byte[] actual)
    {
        var expectedLines = Encoding.UTF8.GetString(expected).Split('\n');
        var actualLines = Encoding.UTF8.GetString(actual).Split('\n');
        for (var line = 0; line < Math.Max(expectedLines.Length, actualLines.Length); line++)
        {
            var left = line < expectedLines.Length ? expectedLines[line].TrimEnd('\r') : "<end of file>";
            var right = line < actualLines.Length ? actualLines[line].TrimEnd('\r') : "<end of file>";
            if (!string.Equals(left, right, StringComparison.Ordinal))
            {
                return $"The transcript differs first at line {line + 1}.\nchecked in: {left}\ngenerated:  {right}";
            }
        }

        return "The transcripts differ only in their line endings or final newline.";
    }
}
