using EtAlii.Adp.Documents;

namespace EtAlii.Adp.Diagram.AzurePipeline;

/// <summary>
/// A job's <c>strategy</c> block as declared, and how many jobs it turns one declaration into.
/// </summary>
/// <param name="Kind">Which strategy it is.</param>
/// <param name="Multiplicity">
/// How many copies of the job will run: the number of <c>matrix</c> entries, the <c>parallel</c>
/// count, or 1 for a job that runs once. Requirement 4.6 asks for this so a job that becomes
/// several at run time does not look like one.
/// </param>
/// <param name="MultiplicityExpression">
/// Set instead of a count where the multiplicity is an expression - a matrix generated by
/// <c>${{ each }}</c>, or <c>parallel: $(slices)</c>. Carried verbatim, and
/// <paramref name="Multiplicity"/> stays 1, because pretending to know a number nobody knows yet
/// would be worse than admitting the count is decided later.
/// </param>
/// <param name="Lines">The lines declaring it.</param>
public sealed record PipelineStrategy(
    PipelineStrategyKind Kind,
    int Multiplicity,
    string MultiplicityExpression,
    LineRange Lines)
{
    /// <summary>The absence of a <c>strategy</c> key.</summary>
    public static PipelineStrategy None { get; } =
        new(PipelineStrategyKind.None, 1, "", new LineRange(0, 0));

    /// <summary>Whether this is one of the three deployment strategies.</summary>
    public bool IsDeployment =>
        Kind is PipelineStrategyKind.RunOnce or PipelineStrategyKind.Rolling or PipelineStrategyKind.Canary;

    /// <summary>Whether the job runs as more than one, or as a number not knowable until it runs.</summary>
    public bool IsMultiplied => Multiplicity > 1 || MultiplicityExpression.Length > 0;
}
