using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using EtAlii.Adp.Context;
using Google.Protobuf;
using Google.Protobuf.Reflection;

namespace EtAlii.Adp.Diagram.DotNetDependencyGraph.Tests.Parity;

/// <summary>
/// How the parity transcript writes what the module answers: one canonical line per row, payload,
/// graph entry and answer, so a change to any of them is a one-line diff of the checked-in file.
/// </summary>
/// <remarks>
/// <para>
/// <b>Deterministic by construction</b>: no timestamps, no absolute paths (the source folder is
/// written as <c>{src}</c>, with forward slashes), invariant number formatting, and every list in
/// the order the code produced it.
/// </para>
/// <para>
/// <b>CRLF, as <c>.gitattributes</c> checks a JSON file out</b>, so the regenerated bytes compare
/// equal to the working file on every machine. The shape follows the hype cycle graph's transcript.
/// </para>
/// </remarks>
internal static class TranscriptText
{
    /// <summary>The writer the transcript uses.</summary>
    public static JsonWriterOptions WriterOptions { get; } = new()
    {
        Indented = true,
        IndentSize = 2,
        NewLine = "\r\n",
        Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
    };

    /// <summary>A string as a JSON literal, so a value's newlines and quotes stay on its line.</summary>
    private static JsonSerializerOptions StringOptions { get; } = new() { Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping };

    // Fields at their default are left out, as the wire leaves them out: the bytes cannot tell them apart.
    private static readonly JsonFormatter _payloadJson = new(JsonFormatter.Settings.Default);

    /// <summary>The lowercase hex sha256 of <paramref name="bytes"/>.</summary>
    public static string Sha256(ReadOnlySpan<byte> bytes) => Convert.ToHexStringLower(SHA256.HashData(bytes));

    /// <summary>A number as the transcript writes it: shortest round-trip, invariant.</summary>
    private static string Number(double value) => value.ToString("R", CultureInfo.InvariantCulture);

    /// <summary>A text as a JSON string literal.</summary>
    public static string Quoted(string? value) => value is null ? "null" : JsonSerializer.Serialize(value, StringOptions);

    /// <summary>A property row as one line.</summary>
    public static string RowLine(ContextPropertyDefinition row)
    {
        var editable = row.ReadOnlyReason.Length > 0 ? $"read-only ({row.ReadOnlyReason})" : "editable";
        var candidates = row.Candidates is { } list ? $" | choices [{string.Join(", ", list.Select(Quoted))}]" : "";
        return $"{row.Id} | {row.Label} | {Quoted(row.Value)} | {row.Editor} | {editable} | group {row.Group}{candidates}";
    }

    /// <summary>A mapped element as one line, its payload decoded to protobuf JSON.</summary>
    public static string PayloadLine(string id, double x, double y, string type, string typeUrl, ReadOnlyMemory<byte> payload, TypeRegistry registry)
    {
        var name = typeUrl[(typeUrl.LastIndexOf('/') + 1)..];
        var descriptor = registry.Find(name) ?? throw new InvalidOperationException($"No payload type {name} is registered.");
        var message = descriptor.Parser.ParseFrom(payload.Span);
        return $"{id} | {type} | {Number(x)}, {Number(y)} | {descriptor.Name} {_payloadJson.Format(message)}";
    }

    /// <summary>The first line at which two transcripts differ, for a failure message a person can act on.</summary>
    public static string FirstDifference(byte[] expected, byte[] actual)
    {
        var expectedLines = Encoding.UTF8.GetString(expected).Split('\n');
        var actualLines = Encoding.UTF8.GetString(actual).Split('\n');
        for (var line = 0; line < Math.Max(expectedLines.Length, actualLines.Length); line++)
        {
            var left = line < expectedLines.Length ? expectedLines[line].TrimEnd('\r') : "<end of file>";
            var right = line < actualLines.Length ? actualLines[line].TrimEnd('\r') : "<end of file>";
            if (!string.Equals(left, right, StringComparison.Ordinal))
            {
                return $"The transcript differs first at line {line + 1}.\nchecked in: {left}\ngenerated:  {right}";
            }
        }

        return "The transcripts differ only in their line endings or final newline.";
    }
}
