<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RootNamespace>EtAlii.Adp</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Core" />
    <PackageReference Include="NetTopologySuite" />
    <PackageReference Include="System.Numerics.Vectors" />
    <PackageReference Include="System.Text.Json" />
    <PackageReference Update="Nerdbank.GitVersioning" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Edit\" />
    <Folder Include="Navigation\" />
  </ItemGroup>

</Project>
