<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all" />
    <PackageReference Include="System.Net.Http.Json" />
  </ItemGroup>

  <ItemGroup>
<!--    <PackageReference Include="Z.Blazor.Diagrams" />-->
    <ProjectReference Include="..\SharedDemo\SharedDemo.csproj" />
  </ItemGroup>

</Project>
