// <auto-generated />
using System;
using EtAlii.Adp.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EtAlii.Adp.Api.Database.Migrations
{
    [DbContext(typeof(AdpDbContext))]
    [Migration("20250216193031_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EtAlii.Adp.Diagram", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Zoom")
                        .HasColumnType("float");

                    b.Property<double>("_diagramPositionX")
                        .HasColumnType("float")
                        .HasColumnName("DiagramPositionX");

                    b.Property<double>("_diagramPositionY")
                        .HasColumnType("float")
                        .HasColumnName("DiagramPositionY");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Diagrams");
                });

            modelBuilder.Entity("EtAlii.Adp.Link", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DiagramId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EndNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EndPort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StartNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StartPort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DiagramId");

                    b.HasIndex("EndNodeId");

                    b.HasIndex("Id");

                    b.HasIndex("StartNodeId");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("EtAlii.Adp.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DiagramId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("_nodePositionX")
                        .HasColumnType("float")
                        .HasColumnName("NodePositionX");

                    b.Property<double>("_nodePositionY")
                        .HasColumnType("float")
                        .HasColumnName("NodePositionY");

                    b.HasKey("Id");

                    b.HasIndex("DiagramId");

                    b.HasIndex("Id");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("EtAlii.Adp.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExternalIdentifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EtAlii.Adp.Diagram", b =>
                {
                    b.HasOne("EtAlii.Adp.User", "Owner")
                        .WithMany("Diagrams")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("EtAlii.Adp.Link", b =>
                {
                    b.HasOne("EtAlii.Adp.Diagram", "Diagram")
                        .WithMany("Links")
                        .HasForeignKey("DiagramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EtAlii.Adp.Node", "EndNode")
                        .WithMany("InboundLinks")
                        .HasForeignKey("EndNodeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EtAlii.Adp.Node", "StartNode")
                        .WithMany("OutboundLinks")
                        .HasForeignKey("StartNodeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Diagram");

                    b.Navigation("EndNode");

                    b.Navigation("StartNode");
                });

            modelBuilder.Entity("EtAlii.Adp.Node", b =>
                {
                    b.HasOne("EtAlii.Adp.Diagram", "Diagram")
                        .WithMany("Nodes")
                        .HasForeignKey("DiagramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diagram");
                });

            modelBuilder.Entity("EtAlii.Adp.Diagram", b =>
                {
                    b.Navigation("Links");

                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("EtAlii.Adp.Node", b =>
                {
                    b.Navigation("InboundLinks");

                    b.Navigation("OutboundLinks");
                });

            modelBuilder.Entity("EtAlii.Adp.User", b =>
                {
                    b.Navigation("Diagrams");
                });
#pragma warning restore 612, 618
        }
    }
}
