// <auto-generated />
using System;
using EtAlii.Adp.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace EtAlii.Adp.Api.Database.Migrations
{
    [DbContext(typeof(AdpDbContext))]
    [Migration("20250208230302_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("EtAlii.Adp.Diagram", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Point>("Position")
                        .IsRequired()
                        .HasColumnType("POINT");

                    b.Property<float>("Zoom")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Diagrams");
                });
#pragma warning restore 612, 618
        }
    }
}
