// <auto-generated />
using System;
using EtAlii.Adp.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EtAlii.Adp.Api.Database.Migrations
{
    [DbContext(typeof(AdpDbContext))]
    [Migration("20250310222750_Added access fields")]
    partial class Addedaccessfields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EtAlii.Adp.Diagram", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowPublicAccess")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ShowInPortal")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowNavigation")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowProperties")
                        .HasColumnType("bit");

                    b.Property<double>("Zoom")
                        .HasColumnType("float");

                    b.Property<double>("_diagramPositionX")
                        .HasColumnType("float")
                        .HasColumnName("DiagramPositionX");

                    b.Property<double>("_diagramPositionY")
                        .HasColumnType("float")
                        .HasColumnName("DiagramPositionY");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Diagrams");
                });

            modelBuilder.Entity("EtAlii.Adp.Link", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DiagramId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SourceNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourcePort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TargetNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TargetPort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DiagramId");

                    b.HasIndex("Id");

                    b.HasIndex("SourceNodeId");

                    b.HasIndex("TargetNodeId");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("EtAlii.Adp.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DiagramId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("_nodePositionX")
                        .HasColumnType("float")
                        .HasColumnName("NodePositionX");

                    b.Property<double>("_nodePositionY")
                        .HasColumnType("float")
                        .HasColumnName("NodePositionY");

                    b.HasKey("Id");

                    b.HasIndex("DiagramId");

                    b.HasIndex("Id");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("EtAlii.Adp.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("EtAlii.Adp.TagGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LinkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("LinkId");

                    b.HasIndex("NodeId");

                    b.ToTable("TagGroups");
                });

            modelBuilder.Entity("EtAlii.Adp.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExternalIdentifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Theme")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TagTagGroup", b =>
                {
                    b.Property<Guid>("TagGroupsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TagGroupsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("TagTagGroup");
                });

            modelBuilder.Entity("EtAlii.Adp.Diagram", b =>
                {
                    b.HasOne("EtAlii.Adp.User", "Owner")
                        .WithMany("Diagrams")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("EtAlii.Adp.Link", b =>
                {
                    b.HasOne("EtAlii.Adp.Diagram", "Diagram")
                        .WithMany("Links")
                        .HasForeignKey("DiagramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EtAlii.Adp.Node", "SourceNode")
                        .WithMany()
                        .HasForeignKey("SourceNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EtAlii.Adp.Node", "TargetNode")
                        .WithMany()
                        .HasForeignKey("TargetNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Diagram");

                    b.Navigation("SourceNode");

                    b.Navigation("TargetNode");
                });

            modelBuilder.Entity("EtAlii.Adp.Node", b =>
                {
                    b.HasOne("EtAlii.Adp.Diagram", "Diagram")
                        .WithMany("Nodes")
                        .HasForeignKey("DiagramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diagram");
                });

            modelBuilder.Entity("EtAlii.Adp.TagGroup", b =>
                {
                    b.HasOne("EtAlii.Adp.Link", "Link")
                        .WithMany("TagGroups")
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EtAlii.Adp.Node", "Node")
                        .WithMany("TagGroups")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Link");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("TagTagGroup", b =>
                {
                    b.HasOne("EtAlii.Adp.TagGroup", null)
                        .WithMany()
                        .HasForeignKey("TagGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EtAlii.Adp.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EtAlii.Adp.Diagram", b =>
                {
                    b.Navigation("Links");

                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("EtAlii.Adp.Link", b =>
                {
                    b.Navigation("TagGroups");
                });

            modelBuilder.Entity("EtAlii.Adp.Node", b =>
                {
                    b.Navigation("TagGroups");
                });

            modelBuilder.Entity("EtAlii.Adp.User", b =>
                {
                    b.Navigation("Diagrams");
                });
#pragma warning restore 612, 618
        }
    }
}
